### ISSUE TITLE
Bug: [Typescript] Failing to declare first parameter of guard breaks type inference in enqueueActions if another guard accepts dynamic parameters

### ISSUE THREAD

**Issue by taraldr** [statelyai/xstate#5014]
### XState version

XState version 5

### Description

Hi, love XState - just ported my teams typescript clients to XState, and came across this bug I think you might find interesting.

Parameter inference seems to break if you have:
1. A guard which fails to declare the first parameter - `()` vs `(_)`
2. Another guard which uses the second parameter - `(_, params: { some: string )}
3. An action using enqueueActions

This results in a typescript error on the action along the lines of, indicating that parameter type inference broke.

```
Type '{ type: "guardWithParams"; params: unknown; }' is not assignable to type '{ type: "guardWithParams"; params: { some: string; }; }'.
```

Workaround is always declaring the first parameter of all guards, even if unused.

@Andarist 

### Expected result

Expected this not to happen.

### Actual result

This happened.

### Reproduction

https://stackblitz.com/edit/vitejs-vite-dwgz2w?file=src%2Fmain.ts&view=editor

### Additional context

v5.16.0

**Comment by taraldr** [comment]
Also observing the same behaviour if you have:

1. An action which fails to declare the first parameter
2. Another action which uses the second parameter
3. A third action using enqueueActions

Repro: https://stackblitz.com/edit/vitejs-vite-kemb2g?file=src%2Fmain.ts&view=editor

**Comment by taraldr** [comment]
Fixed broken repro links were broken.

**Comment by Tetheta** [comment]
Thank you so much for posting this @taraldr I thought I was going crazy.

Been poring over my code for the past few hours trying to figure out why on earth it was complaining about this. In my case I had an action using typed params, which would work alone. But as soon as I added in anything else (guards/actions/etc) it would error on all of them. *Incredibly* frustrating to try and debug as a brand new XState user.

I thought it had to do with my enqueue actions usage or needing to better type my actions, had no idea this was the cause till I decided to work backward from the broken guards instead and saw this issue.

**Comment by alexamy** [comment]
Still exists in the latest version, [xstate@5.23.0](https://github.com/statelyai/xstate/releases/tag/xstate%405.23.0).

**Comment by davidkpiano** [comment]
cc. @Andarist Any ideas here?
