### ISSUE TITLE
Ambiguous machine service ID generation

### ISSUE THREAD

**Issue by Andarist** [statelyai/xstate#524]
##  Description:

Depending on how we pass a machine to invokeConfig it gets assigned an ID in different ways. See attached codesandbox.

## (Bug) Expected result:

Consistent algorithm for assigned IDs for invoked machines.

## (Bug) Actual result:

When not using explicit IDs for the same machine we can assign such IDs:
- machine's ID
- auto generated invocation ID
- service (from config) name might be used

## Link to reproduction:

https://codesandbox.io/s/kind-matsumoto-lvrt9

I'm happy to fix this, but we'd have to establish what is the expected algorithm.

**Comment by Andarist** [comment]
After some thinking today about this:
1. using service name (from config object) as priority value seems OK as it can be done for any type of service (and we can always pass an explicit ID to override it)
2. using auto generated ID as fallback seems also OK as again - it can be done for any type of service in the very same way. It also conforms to what SCXML spec say about ID generation for invoked sessions.

Reusing machine's ID in any situation for that seems to me as bringing more confusion than good and I would vote for removing it altogether.

That being said it could still trip somebody up but that's price for auto-generating things. This would be a major breaking change but I would personally be in favour of dropping support for inline invokeCreators. We still should support expressions there but returned values IMHO should always point to the config object.

**Comment by davidkpiano** [comment]
> Reusing machine's ID in any situation for that seems to me as bringing more confusion than good and I would vote for removing it altogether.

I think in version 5 I'm going to rename the `machine.id` to `machine.name` since the ID should be determined externally, and the machine ID is really for naming purposes currently.

**Comment by Andarist** [comment]
That would definitely be an improvement - less likely somebody tries to use it in unintended way 👍 And it would nicely correlate to that attribute in SCXML

**Comment by davidkpiano** [comment]
This is solved with `_sessionid` (as discussed externally) in 4.7

**Comment by Andarist** [comment]
@davidkpiano `_sessionid` doesn't solve this particular thing. `_sessionid` assign the internal ID, exposes it to executable content and allows for targeting that machine by external entities (if they get that `_sessionid` from elsewhere).

This ticket is about id generation for child services - this happens [here](https://github.com/davidkpiano/xstate/blob/acf7b921b117f2e930eae0c903b1c6776e2a9949/packages/core/src/StateNode.ts#L388-L421) and this affects later what gets assigned as child ID, starting [here](https://github.com/davidkpiano/xstate/blob/acf7b921b117f2e930eae0c903b1c6776e2a9949/packages/core/src/interpreter.ts#L739)

In SCXML we can read that:
> The ids for <send> and <invoke> are subtly different. In a conformant SCXML document, they must be unique within the session, but in the case where the author does not provide them, the processor must generate a new unique ID not at load time but each time the element is executed. Furthermore the attribute 'idlocation' can be used to capture this automatically generated id. Finally note that the automatically generated id for <invoke> has a special format. See 6.4.1 Attribute Details for details. The SCXML processor may generate all other ids in any format, as long as they are unique.
And also:
> The automatically generated identifier must have the form stateid.platformid, where stateid is the id of the state containing this element and platformid is automatically generated. platformid must be unique within the current session.

BTW. I'm not sure if I should reopen this ticket now or should we discuss this while it's closed?

**Comment by davidkpiano** [comment]
This is no longer valid since IDs are now stable for invocations without specified `id`s. In this case, all of the IDs are `"test.initial:invocation[0]"`
